server {
    listen 80;
    server_name joynur-rahman.xyz www.joynur-rahman.xyz;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # React/Vite routing fix
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}